export const SET_CALC_KEY_VALUE = 'SET_CALC_KEY_VALUE';

//SET CALC_OPERATIONS STARTS
export const ADD_NUMBERS = 'ADD_NUMBERS';
export const SUBTRACT_NUMBERS = 'SUBTRACT_NUMBERS';
export const MULTIPLY_NUMBERS = 'MULTIPLY_NUMBERS';
export const DIVIDE_NUMBERS = 'DIVIDE_NUMBERS';
export const APPLY_PERCENT = 'APPLY_PERCENT';
export const SWITCH_OPERATORS = 'SWITCH_OPERATORS';

export const CALCULATE = 'CALCULATE';

export const SHOW_TOTAL_VALUE = 'SHOW_TOTAL_VALUE';

export const EVALUATE_ERROR = 'EVALUATE_ERROR';
export const EVALUATE_SUCCESS = 'EVALUATE_SUCCESS';

export const CLEAR_CALC_EXPRESSION = 'CLEAR_CALC_EXPRESSION';
export const CLEAR_LAST_ENTRY = 'CLEAR_LAST_ENTRY';
