export {
  setCalcKeyValue,
  addNumbers,
  subtractNumbers,
  multiplyNumbers,
  divideNumbers,
  applyPercent,
  switchOperators,
  calculate,
  showTotal,
  evaluateError,
  evaluateSuccess,
  clearCalcExpression,
  clearLastEntry,
} from './calcActions';
